version: '3.3'

services:
  redis:
    image: redis
    container_name: nap_redis
    restart: always
    ports:
      - '${REDIS_PORT}:6379'

  db:
    image: ${DB_TYPE}:latest
    container_name: nap_db
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

